# Generated by Django 3.1.7 on 2021-03-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
