# Generated by Django 3.1.7 on 2021-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_details',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
