# Generated by Django 3.1.7 on 2021-03-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empname',
            new_name='name',
        ),
    ]
