# Generated by Django 3.1.7 on 2021-03-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Project', '0002_auto_20210325_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='empname',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
