# Generated by Django 3.1.7 on 2021-03-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Project', '0003_auto_20210326_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
